def pr_generator(files, diff_summary, pr_type, issue=None):
    issue_line = f"Fixes #{issue}" if issue else "No linked issue."

    return f"""
## Description
This PR introduces automated changes generated by the Auto PR Writer.

## Changes
- Files changed: {", ".join(files)}
- Summary: {diff_summary}

## Type of Change
- {pr_type}

## Related Issue
{issue_line}

## Checklist
- [x] Tested locally
- [x] No breaking changes
""".strip()
